### ISSUE TITLE
Add ability to set initial size of pip

### ISSUE THREAD

**Issue by AlexByte** [WICG/picture-in-picture#122]

**Comment by beaufortfrancois** [comment]
@AlexByte Can you share more about why having website to decide to the initial size of the Picture-in-Picture window would be useful?

**Comment by AlexByte** [comment]
Because initial size of window in picture-in-picture-chrome-extension is small for me. https://github.com/beaufortfrancois/picture-in-picture-chrome-extension/issues/9#issuecomment-414673181

**Comment by beaufortfrancois** [comment]
@mounirlamouri Shall we revisit Chrome default size? Or shall we persist PiP window sizes across sessions?

**Comment by AlexByte** [comment]
I guess persistance is better.

**Comment by mounirlamouri** [comment]
@beaufortfrancois if we want to change Chrome's default behaviour, we may want to open a Chrome issue instead of a spec one :) Probably not the right place to discuss Chrome implementation concerns.

IIRC, the API had a size hint but we dropped it because Chrome wasn't planning to use it nor Safari.

**Comment by beaufortfrancois** [comment]
I'll close this issue so that we continue discussing this implementation issue at https://bugs.chromium.org/p/chromium/issues/detail?id=949570#
