### ISSUE TITLE
Add ability to disable some "auto-pip" behavior

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/picture-in-picture#25]
Some browsers may have some kind of "auto-pip" behavior such as [Chrome on Android O](http://www.androidpolice.com/2017/06/25/google-chrome-adds-support-picture-picture-video-android-O/). It would be nice to have a way to prevent this behavior with the Picture In Picture Web API.

It could be an HTML attribute similar to [`disableRemotePlayback`](https://w3c.github.io/remote-playback/#disabling-remote-playback):

```html
<video disableAutoPictureInPicture>
```

Or an event listener we could use to prevent element to enter pip:

```js
video.addEventListener('beforepictureinpicture', event => {
  event.preventDefault();
});
```

What do you think @mounirlamouri @jernoble?

**Comment by mounirlamouri** [comment]
The issue with the event listener is that we couldn't implement it on Chrome Android as the system only allows us to auto-PIP in a specific event handler so we couldn't ask the renderer process whether it's okay to PIP. The attribute sgtm, we might want to shorten to `disableAutoPIP` but that's not very important.

Given that Chrome and Safari implements auto-pip, I think we could even define what it is in the spec.

**Comment by jernoble** [comment]
@beaufortfrancois, what’s the use case for blocking auto-PiP?

**Comment by beaufortfrancois** [comment]
Chrome will stop auto-PiP in some conditions: when video is ended or video exits fullscreen for instance. We're concerned that some websites may use these heuristics to block auto-PiP which would be a bad experience for developers & users.

Moreover, in the same way that some websites want to disable media remote playback for legal reasons, it could apply to PiP as well.

**Comment by jernoble** [comment]
@beaufortfrancois I’m not sure I understand. You’re concerned that websites will “trick” Chrome into not automatically entering PiP by somehow simulating that the video has ended or is exiting full screen? I admit, I don’t have a firm grasp on when Android’s Auto PiP feature will kick in, but it feels like simulating such a thing is going to be incredibly difficult. It would be much easier for a website to listen for the event to fire when the video is in PiP and, e.g. remove the video’s src. (YouTube already does this with the Visibility API to block playback in non-visible tabs on Mobile Safari.)

I’m concerned that a web feature for “don’t do Chrome’s automatic PiP behavior” is going to turn into a “don’t allow the user to PiP ever” feature, and will be abused.

And let’s be honest, because this has come up in other contexts: I am aware of no “legal reasons” for blocking PiP. I am aware of many *business reasons* for blocking PiP. The two are not the same thing.

**Comment by Melatonin64** [comment]
The following feature request contains a use-case where disabling auto PIP would be desirable:
https://crbug.com/772259

Only a quarter of the [video](https://video.helloeko.com/v/MOwJdM) is being displayed, and going into PiP mode reveals the entire video frame.

**Comment by beaufortfrancois** [comment]
I'm thinking about this at https://github.com/WICG/picture-in-picture/pull/28.
WDYT?

**Comment by beaufortfrancois** [comment]
#28 addresses this issue.
